### PR TITLE
Migrate to ink v3

### PR DESCRIPTION
**Pull request by omjadas**

### CODE REVIEW

**Comment by omjadas** [comment]
@JureSotosek bump

**Comment by JureSotosek** [comment]
@omjadas I will check this over the weekend. Thanks for the PR 🙏🏼

**Comment by JureSotosek** [comment]
Can you do a few more things:
- Fix the examples. I think using `span` is not supported anymore? When I try running the examples I get no output. You can remove the `span`s and everything in the examples and just return the `Divider` components.
- Add an `examples` command that will transpile and run both of the examples. You can use `@babel/node` maybe?

@omjadas Thanks for the PR again ✌🏼

**Comment by omjadas** [comment]
@JureSotosek done

**Comment by JureSotosek** [comment]
@omjadas Looks good 👍🏼 Thanks 🙏🏼

**Comment by omjadas** [comment]
@JureSotosek this should probably be a major release, since the syntax for colours in ink v3 is not backwards compatible with ink v2

**Comment by JureSotosek** [comment]
@omjadas Yeah, I'm sorting this out now.

**Pull request merged**
