### PR TITLE
Migrate to ink v2

### PR DESCRIPTION
**Pull request by LitoMore**
### Changes

- Migrate ink to v2
- Use [ink-testing-library](https://github.com/vadimdemedes/ink-testing-library) for test
- Add [XO](https://github.com/xojs/xo) code style
- Upgrade `babel` to v7

### CODE REVIEW

**Comment by LitoMore** [comment]
@JureSotosek ping

**Comment by JureSotosek** [comment]
@LitoMore Sorry for the delay. Thanks for migrating this 🎉

**Comment by JureSotosek** [comment]
@LitoMore Really nice job man 

The only thing is, you should have used the semantic-release commit messaging but I fixed that 🙌🏼

**Pull request merged**
